// pages/user/login.js（ログインページ）

import Head from "next/head";
import { useState } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const handleSubmit = async (e) => {
    try {
      const response = await fetch("http://localhost:3000/api/user/login", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          password: password,
        }),
      });
      const jsonData = await response.json();
      localStorage.setItem("token", jsonData.token);
      alert(jsonData.message);
    } catch (error) {
      alert("ログイン失敗");
    }
  };
  return (
    <>
      <Head>
        <title>Tasting Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {/* <Login /> */}
        <main className={styles.main}>
          <h1 className={styles.title}>Tasting Note</h1>
          <div className={styles.login_btn_box}>
            <form onSubmit={handleSubmit}>
              <input
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                type="text"
                name="email"
                placeholder="メールアドレス"
                required
              />
              <input
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                type="text"
                name="password"
                placeholder="パスワード"
                required
              />
              <button className={styles.login_btn}>
                <a href="">ログイン</a>
              </button>
            </form>
          </div>
        </main>
      </div>
    </>
  );
}
Login();
