//仮フォルダに収納しているファイル
import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import jwt from "jsonwebtoken";
import Link from "next/link";

// import Image from "next/image";
// import { Top } from "@/components/top";
// import { Sign } from "@/components/Sign";

const inter = Inter({ subsets: ["latin"] });
// const secret_key = "tastingcoffee";
export default function Home() {
  return (
    <>
      <Head>
        <title>Tasting Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.main_contents}>
            {" "}
            <div className={styles.top}>
              <h1 className={styles.title}>Tasting Note</h1>
              <nav className={styles.top_nav}>
                <ul className={styles.top_nav_list}>
                  <li className={styles.top_nav_item}>
                    <Link href="top_menu">START</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
Home();
